ElectroShop/Models/PostTopic.cs
namespace ElectroShop
{ 
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


    public class PostTopic
    {
        public int PostId { get; set; }
        public string PostName { get; set; }
        public string PostImg { get; set; }
        public int PostStatus { get; set; }
        public string TopicName { get; set; }
        public DateTime PostCreated_At { get; set; }
    }
}

ElectroShop/Models/ProductCategory.cs
namespace ElectroShop
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


    public class ProductCategory
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductImg { get; set; }
        public int ProductStatus { get; set; }
        public int? ProductDiscount { get; set; }
        public string CategoryName { get; set; }
        public double ProductPriceSale { get; set; }
        public double ProductPrice { get; set; }
        public DateTime ProductCreated_At { get; set; }
        
            
    }
}

ElectroShop/Areas/Admin/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectroShop.Models;

namespace ElectroShop.Areas.Admin.Controllers
{
    public class ContactController : BaseController
    {
        private ElectroShopDbContext db = new ElectroShopDbContext();

        public ActionResult Index()
        {
            ViewBag.countTrash = db.Contacts.Where(m => m.Status == 0).Count();
            return View(db.Contacts.Where(m => m.Status == 1).ToList());
        }
        public ActionResult Trash()
        {
            return View(db.Contacts.Where(m => m.Status == 0).ToList());
        }

        public ActionResult Reply(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại liên hệ từ khách hàng!", "danger");
                return RedirectToAction("Index", "Contact");
            }
            MContact mContact = db.Contacts.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại liên hệ từ khách hàng!", "danger");
                return RedirectToAction("Index", "Contact");
            }
            return View(mContact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Reply(mContact mContact)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        mContact.Status = 2;
        //        mContact.Updated_at = DateTime.Now;
        //        mContact.Updated_by = 1;

        //        String content = System.IO.File.ReadAllText(Server.MapPath("~/Areas/Admin/Views/Mail/D_Mail.html"));
        //        content = content.Replace("{{FullName}}", mContact.Fullname);
        //        content = content.Replace("{{Reply}}", mContact.Reply);
        //        content = content.Replace("{{RQ}}", mContact.Detail);
        //        content = content.Replace("{{AdminName}}", Session["User_Admin"].ToString());
        //        String subject = "Phản hồi liên hệ từ Giadunghiendai.com";
        //        //new MailHelper().SendMail(mContact.Email, subject, content);

        //        db.Entry(mContact).State = EntityState.Modified;
        //        db.SaveChanges();
        //        Notification.set_flash("Đã trả lời liên hệ!", "success");
        //        return RedirectToAction("Index");
        //    }
        //    return View(mContact);
        //}
        public ActionResult Reply(MContact mContact)
        {
            if (ModelState.IsValid)
            {
                mContact.Flag = 1;
                mContact.Updated_at = DateTime.Now;
                mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());

                db.Entry(mContact).State = EntityState.Modified;
                db.SaveChanges();
                Notification.set_flash("Đã trả lời liên hệ!", "success");
                return RedirectToAction("Index");
            }
            return View(mContact);
        }

        public ActionResult DelTrash(int id)
        {
            MContact mContact = db.Contacts.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index");
            }
            mContact.Status = 0;
            mContact.Updated_at = DateTime.Now;
            mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mContact).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Ném thành công vào thùng rác!" + " ID = " + id, "success");
            return RedirectToAction("Index");
        }

        public ActionResult ReTrash(int? id)
        {
            MContact mContact = db.Contacts.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại danh mục!", "warning");
                return RedirectToAction("Trash", "Contact");
            }
            mContact.Status = 1;
            mContact.Updated_at = DateTime.Now;
            mContact.Updated_by = int.Parse(Session["Admin_ID"].ToString());
            db.Entry(mContact).State = EntityState.Modified;
            db.SaveChanges();
            Notification.set_flash("Khôi phục thành công!" + " ID = " + id, "success");
            return RedirectToAction("Trash", "Contact");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index");
            }
            MContact mContact = db.Contacts.Find(id);
            if (mContact == null)
            {
                Notification.set_flash("Không tồn tại!", "warning");
                return RedirectToAction("Index");
            }
            return View(mContact);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MContact mContact = db.Contacts.Find(id);
            db.Contacts.Remove(mContact);
            db.SaveChanges();
            Notification.set_flash("Đã xóa vĩnh viễn liên hệ!", "danger");
            return RedirectToAction("Index");
        }
    }
}

ElectroShop/Controllers/ModuleController.cs
using ElectroShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectroShop.Controllers
{
    public class ModuleController : Controller
    {
        private ElectroShopDbContext db = new ElectroShopDbContext();
        // GET: Module
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Header()
        {
            return View("_Header");
        }
        public ActionResult CategorySearch()
        {
            var list = db.Categorys
               .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategorySearch",list);
        }
        public ActionResult Cart()
        {
            return View("_Cart");
        }
        public ActionResult Navbar()
        {
            return View("_Navbar");
        }
        public ActionResult ProductView()
        {
            return View("_ProductView");
        }
        public ActionResult LatestNew()
        {
            var list = db.Posts
               .Where(m => m.Status == 1 && m.Type == "post")
               .Take(3)
               .OrderByDescending(m => m.Created_At )
               .ToList();
            return View("_LatestNew", list);
        }
        public ActionResult Brand()
        {
            return View("_Brand");
        }
        public ActionResult CompanyFacality()
        {
            return View("_CompanyFacality");
        }
        public ActionResult Footer()
        {
            return View("_Footer");
        }
        public ActionResult Copyright()
        {
            return View("_Copyright");
        }
        public ActionResult LinkHeader()
        {
            return View("_LinkHeader");
        }
        public ActionResult LinkFooter()
        {
            return View("_LinkFooter");
        }
        public ActionResult Category()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_Category", list);
        }
        public ActionResult CategoryFooter()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategoryFooter", list);
        }
        public ActionResult ProductNew()
        {
            var list = db.Products
               .Where(m => m.Status == 1 && m.Discount != 0)
               .Take(4)
               .ToList();
            return View("_ProductNew", list);
        }

        public ActionResult Sale()
        {
            var list = db.Products
               .Where(m => m.Status == 1)
               .Take(3)
               .OrderByDescending(m=>m.Created_at)
               .ToList();
            return View("_Sale", list);
        }
        public ActionResult SlideShow()
        {
            return View("_SlideShow",db.Sliders.Where(m=>m.Status!=0).ToList());
        }
        public ActionResult ListPage()
        {
            var list = db.Posts
              .Where(m => m.Status == 1 && m.Type=="page")
              .OrderByDescending(m => m.Created_At)
              .ToList();
            return View("_ListPage",list);
        }
        public ActionResult MainMenu()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Position=="mainmenu")
              .ToList();
            return View("_MainMenu", list);
        }
        public ActionResult MainMenuMobile()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Type == "custom")
              .ToList();
            return View("_MainMenuMobile", list);
        }
        public ActionResult ListCate()
        {
            return View("_ListCate", db.Categorys.Where(m => m.Status != 0 && m.ParentId==0).ToList());
        }
        public ActionResult Posts()
        {
            var list = db.Topics 
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("Posts", list);
        }
        public ActionResult PostHome(int topid)
        {
            List<int> listtopid = new List<int>();
            listtopid.Add(topid);

            var list2 = db.Topics
                .Where(m => m.ParentId == topid).Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listtopid.Add(id2);
                var list3 = db.Topics
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id).ToList();
                foreach (var id3 in list3)
                {
                    listtopid.Add(id3);
                }
            }

            var list = db.Posts
                .Where(m => m.Status == 1 && listtopid
                .Contains(m.Topid))
                .Take(12)
                .OrderByDescending(m => m.Created_At);

            return View("PostHome", list);
        }
        public ActionResult ListTopic()
        {
            return View("ListTopic", db.Topics.Where(m => m.Status != 0 && m.ParentId == 0).ToList());
        }
        public ActionResult PListPage()
        {
            var list = db.Posts
                .Where(m => m.Status == 1 && m.Type == "page");
            return View("PListPage", list);
        }
    }
}

ElectroShop/Views/Site/Home.cshtml
@model IEnumerable<ElectroShop.Models.MCategory>
@{
    ViewBag.Title = "Chuyên LapTop Bổ Rẻ";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Navbar", "Module")
@Html.Action("ProductView", "Module")
<section class="main-content-section-full-column">
    @foreach (var cat in Model)
    {
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="featured-products-area">
                        <div class="left-title-area">
                            <h2 class="left-title">@cat.Name</h2>
                        </div>
                        <div class="row">
                            <div class="feartured-carousel">
                                @Html.Action("ProductHome", "Site", new { catid = cat.Id })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>
@Html.Action("LatestNew", "Module")

ElectroShop/Views/Site/PostDetail.cshtml
@model ElectroShop.Models.MPost
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.Raw(Model.Detail)
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="left-title-area">
                <h2 class="left-title">Bài viết cùng danh mục</h2>
            </div>
        </div>
        <div class="related-product-area featured-products-area">
            <div class="col-sm-12">
                <div class=" row">
                    <div class="related-product">
                        @foreach (var item in ViewBag.listother)
                        {
                            <div class="item">
                                <div class="single-product-item">
                                    <div class="product-image">
                                        <a href="~/@item.Slug"><img src="~/Public/library/post/@item.Img" alt="@item.Title" height="120px;" /></a>
                                    </div>
                                    <div class="product-info">
                                        <a href="@item.Slug">@item.Title</a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ElectroShop/Views/Site/PostPage.cshtml
@model ElectroShop.Models.MPost
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            @Html.Raw(Model.Detail)
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h2 style="color:darkgoldenrod">Xem thêm</h2>
            @Html.Action("PListPage","Module")
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

ElectroShop/Views/Site/PostTopic.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ElectroShop.Models.MPost>
@{ ViewBag.Title = ViewBag.CatName;
                Layout = "~/Views/Shared/_LayoutSite.cshtml"; }

<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="~/">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>@ViewBag.CatName</span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <!-- PRODUCT-LEFT-SIDEBAR START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title pro-g-page-title">Danh mục bài viết</h2>
                    <!-- SINGLE SIDEBAR ENABLED FILTERS START -->
                    <ul>
                        @Html.Action("ListTopic", "Module")
                    </ul>
                </div>
                <!-- PRODUCT-LEFT-SIDEBAR END -->
                <!-- SINGLE SIDEBAR TAG START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title">Tags </h2>
                    <div class="category-tag">
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in Model)
                            {
                <li class="gategory-product-list col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="single-product-item">
                        <div class="product-image">
                            <a href="~/@item.Slug"><img src="~/Public/library/post/@item.Img" alt="@item.Title" width="120px;" /></a>
                            
                            
                        </div>
                        <div class="product-info">
                            <div class="customar-comments-box">
                               @* <div class="rating-box">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>*@
                                @*<div class="review-box">
                                        <span>1 Review(s)</span>
                                    </div>*@
                            </div>
                            <a href="~/@item.Slug">@item.Title</a>
                            
                        </div>
                    </div>
                </li>}
                        </ul>
                    </div>
                </div>
                <div class="product-shooting-result product-shooting-result-border">

                    @*<div class="showing-item">
                        <span>Showing 1 - 12 of @ViewBag.Sl</span>
                    </div>*@
                    <div class="showing-next-prev">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { slug = ViewBag.Slug, page }))

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

ElectroShop/Views/Site/Product.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ElectroShop.Models.MProduct>
@{
    ViewBag.Title = "Tất cả sản phẩm";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="~/">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>Tất cả sản phẩm</span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <!-- PRODUCT-LEFT-SIDEBAR START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title pro-g-page-title">Danh mục sản phẩm</h2>
                    <!-- SINGLE SIDEBAR ENABLED FILTERS START -->
                    <ul>
                        @Html.Action("ListCate", "Module")
                    </ul>
                </div>
                <!-- PRODUCT-LEFT-SIDEBAR END -->
                <!-- SINGLE SIDEBAR TAG START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title">Tags </h2>
                    <div class="category-tag">
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in Model)
                            {
                                <li class="gategory-product-list col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                    <div class="single-product-item">
                                        <div class="product-image">
                                            <a href="~/@item.Slug"><img src="~/Public/library/product/@item.Image" alt="@item.Name" /></a>
                                            @if (item.Discount != 0)
                                            {
                                                <a href="#" class="new-mark-box">new</a> }
                                            else
                                            { @*<a href="#" class="new-mark-box">new</a>*@}
                                            <div class="overlay-content">
                                                <ul>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-search"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-shopping-cart"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-retweet"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-heart-o"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product-info">
                                            <div class="customar-comments-box">
                                                <div class="rating-box">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                @*<div class="review-box">
                                                        <span>1 Review(s)</span>
                                                    </div>*@
                                            </div>
                                            <a href="~/@item.Slug">@item.Name</a>
                                            <div class="price-box">
                                                <span class="price">@String.Format("{0:0,0₫}", item.ProPrice)</span>
                                                <del><span class="price" style="color:red">@String.Format("{0:0,0₫}", item.Price)</span></del>

                                            </div>
                                        </div>
                                    </div>
                                </li>
}
                        </ul>
                    </div>
                </div>
                <div class="product-shooting-result product-shooting-result-border">

                    @*<div class="showing-item">
                        <span>Showing 1 - 12 of @ViewBag.Sl</span>
                    </div>*@
                    <div class="showing-next-prev">
                        @Html.PagedListPager(Model, page => Url.Action("Product", new { page }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

ElectroShop/Views/Site/ProductCategory.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ElectroShop.Models.MProduct>
@{
    ViewBag.Title = ViewBag.CatName;
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="~/">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>@ViewBag.CatName</span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <!-- PRODUCT-LEFT-SIDEBAR START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title pro-g-page-title">Danh mục sản phẩm</h2>
                    <!-- SINGLE SIDEBAR ENABLED FILTERS START -->
                    <ul>
                        @Html.Action("ListCate", "Module")
                    </ul>
                </div>
                <!-- PRODUCT-LEFT-SIDEBAR END -->
                <!-- SINGLE SIDEBAR TAG START -->
                <div class="product-left-sidebar">
                    <h2 class="left-title">Tags </h2>
                    <div class="category-tag">
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                        <a href="#">Phụ kiện</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in Model)
                            {
                                <li class="gategory-product-list col-lg-3 col-md-4 col-sm-6 col-xs-12">
                                    <div class="single-product-item">
                                        <div class="product-image">
                                            <a href="~/@item.Slug"><img src="~/Public/library/product/@item.Image" alt="@item.Name" /></a>
                                            @if (item.Discount != 0)
                                            {
                                        <a href="#" class="new-mark-box">new</a> 
                                            }
                                             else
                                               {
                                                  @*<a href="#" class="new-mark-box">new</a>*@
                                                }
                                            <div class="overlay-content">
                                                <ul>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-search"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-shopping-cart"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-retweet"></i></a></li>
                                                    <li><a href="#" title="Quick view"><i class="fa fa-heart-o"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product-info">
                                            <div class="customar-comments-box">
                                                <div class="rating-box">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                </div>
                                                @*<div class="review-box">
                                                    <span>1 Review(s)</span>
                                                </div>*@
                                            </div>
                                            <a href="~/@item.Slug">@item.Name</a>
                                            <div class="price-box">
                                                <span class="price">@String.Format("{0:0,0₫}", item.ProPrice)</span>
                                                <del><span class="price" style="color:red">@String.Format("{0:0,0₫}", item.Price)</span></del>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="product-shooting-result product-shooting-result-border">

                    <div class="showing-item">
                        <span>Showing 1 - 12 of @ViewBag.Sl</span>
                    </div>
                    <div class="showing-next-prev">
                        @Html.PagedListPager(Model, page => Url.Action("Index", "Site", new { slug = ViewBag.Slug, page }))

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>